/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.17.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./CwReceipt.types";
import * as _1 from "./CwReceipt.client";
import * as _2 from "./CwReceipt.message-composer";
import * as _3 from "./CwReceipt.react-query";
import * as _4 from "./CwReceipt.recoil";
export namespace contracts {
  export const CwReceipt = { ..._0,
    ..._1,
    ..._2,
    ..._3,
    ..._4
  };
}